### PR TITLE
Scaffolding commit to get us started

### PR DESCRIPTION
**Pull request by kris-nova**
Adds basic repo scaffolding, none of this is set in stone - just gets us started - please refactor as we see fit!

### CODE REVIEW

**Comment by Grillz** [comment]
I like the start, but can we avoid checking in the vendored code, it just makes things messy 😄

**Comment by kris-nova** [comment]
We want it so go get works - we will pull it out once we start offering builds

**Comment by kris-nova** [comment]
Sorry On phone - you know what I mean by go get right?

**Comment by Grillz** [comment]
sounds good

**Pull request merged**
